### ISSUE TITLE
Configurable charset

### ISSUE THREAD

**Issue by Trekels** [yappabe/docker-mysql#5]
Currently there is no posibility to set a different charset, in some cases a different is needed, take `utf8mb4` for example, this would support storing 4 bytes instead of 3. Allowing one to perist emoticons 🎉 .

Would you be open to a pr that if a env var with a charset is set, a mysql.cnf file is generated to change the mysql charset and collation to this value.

**Comment by veloxy** [comment]
I don't think the images need a complicated config for something you could just drop an recreate. Though it wouldn't hurt to have proper defaults, those can be configured in the config file:
```
[mysqld]
character-set-server=utf8
collation-server=utf8_general_ci
```

**Comment by veloxy** [comment]
Maybe check out the official images, see how they do it? I think we should be extending them because the current ones we extend are deprecated, there's an open ticket for that with no responses.

**Comment by Trekels** [comment]
Found a way around it, but the other images should be extending the official one indeed
